language: node_js
node_js:
- '4.2'
cache:
  directories:
  - node_modules
env:
  global:
  - ENCRYPTION_LABEL: "1b0babe6137a"
  - COMMIT_AUTHOR_EMAIL: "generator@cometvisu.org"
before_install:
- npm install -g grunt-cli
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install gcc-5 g++-5
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
- sudo update-alternatives --set gcc /usr/bin/gcc-5
- mkdir cache
install:
- npm install
- "./node_modules/protractor/bin/webdriver-manager update --standalone --firefox"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 3
script:
- grunt jscs
- grunt karma:travis
- grunt e2e
- doc/deploy.sh
- grunt coveralls
