language: python
dist: trusty
node_js:
- '4.2'
python:
- '3.5'
cache:
  directories:
  - node_modules
  - $HOME/.cache/pip
  - downloads
env:
  - CV_BUILD="test"
  - CV_BUILD="docs" ENCRYPTION_LABEL="4c79fec0aeb9" COMMIT_AUTHOR_EMAIL="generator@cometvisu.org" CV_BROWSER=Chrome CV_VERSION=stable
before_install:
- mkdir -p downloads
- nvm install 4.2
- if [ "$CV_BUILD" == "docs" ]; then sudo ./utils/travis/browser-setup.sh; fi
- if [ "$CV_BUILD" == "docs" ]; then export CHROME_BIN=`pwd`/chrome/google-chrome; fi
- if [ "$CV_BUILD" == "docs" ] && ! [ -e downloads/plantuml.deb ]; then wget -O downloads/plantuml.deb http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb; fi
- mkdir cache
install:
- npm install -g grunt-cli
- if [ "$CV_BUILD" == "test" ]; then cd external/qooxdoo; fi
- if [ "$CV_BUILD" == "test" ]; then npm install; fi
- if [ "$CV_BUILD" == "test" ]; then grunt setup; fi
- if [ "$CV_BUILD" == "test" ]; then cd ../../; fi
- npm install
- if [ "$CV_BUILD" == "test" ]; then virtualenv -p /usr/bin/python2.7 --distribute temp-python --system-site-packages; fi
- if [ "$CV_BUILD" == "test" ]; then source temp-python/bin/activate; fi
- if [ "$CV_BUILD" == "test" ]; then sudo pip install -r utils/requirements.txt; fi #used by the generator
- if [ "$CV_BUILD" == "test" ]; then ./generate.py source -sI; fi
- if [ "$CV_BUILD" == "test" ]; then deactivate; fi
- "./node_modules/protractor/bin/webdriver-manager update"
- if [ "$CV_BUILD" == "docs" ]; then sudo pip install -r utils/requirements.txt; fi # for documentation
- if [ "$CV_BUILD" == "docs" ]; then sudo apt-get install libxml2-dev libxslt-dev graphviz; fi
- if [ "$CV_BUILD" == "docs" ]; then sudo dpkg -i downloads/plantuml.deb; fi
- if [ "$CV_BUILD" == "docs" ]; then utils/travis/npm-setup.sh; fi
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 3
script:
- if [ "$CV_BUILD" == "test" ]; then source temp-python/bin/activate; fi
- if [ "$CV_BUILD" == "test" ]; then grunt jscs; fi
- if [ "$CV_BUILD" == "test" ]; then source temp-python/bin/activate; fi
- if [ "$CV_BUILD" == "test" ]; then ./generate.py lint; fi
- if [ "$CV_BUILD" == "test" ]; then deactivate; fi
- if [ "$CV_BUILD" == "test" ]; then grunt karma:travis; fi
- if [ "$CV_BUILD" == "test" ]; then grunt e2e-chrome; fi
- if [ "$CV_BUILD" == "docs" ]; then utils/travis/deploy.sh; fi
after_success:
- if [ "$CV_BUILD" == "test" ]; then grunt coveralls; fi

