language: node_js
node_js:
  - '4.2'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g grunt-cli
  - apt-get install python-software-properties
  - add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - apt-get update
  - apt-get install gcc-5 g++-5
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - update-alternatives --set gcc /usr/bin/gcc-5
install:
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update --standalone --firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - sleep 3
script:
  - grunt jscs
  - grunt karma:travis
  - grunt e2e
  - grunt coveralls