openapi: 3.0.1
info:
  description: ''
  version: 1.0.0
  title: CometVisu Manager backend
tags:
  - name: fs
    description: Filesystem handling
paths:
  '/fs':
    parameters:
      - name: path
        in: query
        description: Relative path inside the config folder
        required: true
        schema:
          type: string
    get:
      tags:
        - fs
      summary: Return directory listing or file content
      description: Returns a list of files/directories if the requested path pointed to a directory or the content of the file otherwise
      operationId: read
      x-exegesis-controller: FsController
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadResponse'
            text/*:
              schema:
                type: string
        '403':
          description: Not allowed
        '404':
          description: Path not found
    post:
      tags:
        - fs
      summary: Create a new file or folder on the host
      description: ''
      operationId: create
      x-exegesis-controller: FsController
      requestBody:
        description: Content of the file (empty when creating folder)
        content:
          text/*:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
        '403':
          description: Not allowed
        '406':
          description: File exists
    put:
      tags:
        - fs
      summary: Update an existing file
      description: ''
      operationId: update
      x-exegesis-controller: FsController
      requestBody:
        description: Content of the file
        required: true
        content:
          text/*:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
        '403':
          description: Not allowed
        '406':
          description: File does not exist
    delete:
      tags:
        - fs
      summary: Deletes a file/folder
      description: ''
      operationId: delete
      x-exegesis-controller: FsController
      responses:
        '200':
          description: successful operation
        '403':
          description: Not allowed
        '404':
          description: File/Folder not found
        '406':
          description: Folder not empty
components:
  schemas:
    ReadResponse:
      oneOf:
        - $ref: '#/components/schemas/DirContent'
    DirContent:
      type: array
      items:
        $ref: '#/components/schemas/FsEntry'
    FsEntry:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: ['dir', 'file']
        parentFolder:
          type: string
        hasChildren:
          type: boolean
        readable:
          type: boolean
          default: false
        writeable:
          type: boolean
          default: false
externalDocs:
  description: Find out more about CometVisu
  url: 'https://www.cometvisu.org'
